### ISSUE TITLE
Add option for hover styles/animation

### ISSUE THREAD

**Issue by iljapanic** [luukdv/hamburger-react#53]
I would love to add subtle hover animation, similar like this one from [Pangram Pangram](https://pangrampangram.com/):
![screenshot-2022-05-04-The Pangram Pangram® Font Starter Pack - Edition 4 0 – Pangram Pangram Foundry -HvxD78au](https://user-images.githubusercontent.com/1295321/166813899-4db8ab34-8e04-4f73-aab7-fb8250abaf14.gif)

I've tried manually overriding the CSS like this:

```css
.hamburger-react:hover div:first-of-type > div {
  top: 16px !important;
}

.hamburger-react:hover div:last-of-type > div {
  top: 30px !important;
}
```

I could live with the fixed values and those `!important`s if it worked well, but this approach results in broken styling when the menu is open and still hovered on:
![screenshot-2022-05-04-Critical Perspectives on Public Art   Innovation — Ilja Panić -dJaHeNE8](https://user-images.githubusercontent.com/1295321/166814514-bab7cec5-41c1-48d3-b880-c4454192e787.gif)

It's probably possible to find a way to hack around it to make it work, but I was wondering if you are considering to add some styling options for hover state? 

Thank you for such a straight-forward and clean menu implementation. I'm happy with it with or without hover 🙏
