### ISSUE TITLE
How can I adjust the visibility?

### ISSUE THREAD

**Issue by TavukDoner7528** [luukdv/hamburger-react#56]
# Hello first of all.

I've used this and this
```css
.hamburger {
  visibility: hidden;
}
```
and
```css
.hamburger {
  display: none;
}
```
to toggle visibility but none of these worked.

Is there any other way to do this?

### Thanks in advance for your help!
