### ISSUE TITLE
How can I give it custom styling specifically `z-index : 2`?

### ISSUE THREAD

**Issue by souravdewett** [luukdv/hamburger-react#57]

**Comment by luukdv** [comment]
Hey! You can do this in two ways:

```css
.hamburger-react { z-index: 2 }
```

```jsx
<div style={{ zIndex: 2 }}><Hamburger /></div>
```
